apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-mongo-primary
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-1
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-aa36f1ac::fsap-0e00c4f011d6087f8

--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-1
spec:
  volumeName: efs-pv-mongo-primary
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-1
  resources:
    requests:
      storage: 8Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-mongo-secondary
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-1
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-aa36f1ac::fsap-0e00c4f011d6087f8

--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-2
spec:
  volumeName: efs-pv-mongo-secondary
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-1
  resources:
    requests:
      storage: 8Gi
